# Generated by Django 4.2.7 on 2026-06-02 17:00

from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("student", "Студент"),
                            ("staff", "Преподаватель"),
                            ("admin", "Администратор"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=120)),
                ("identifier", models.CharField(max_length=40, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("access_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("location", models.CharField(max_length=160)),
                ("is_open", models.BooleanField(default=False)),
                ("opened_until", models.DateTimeField(blank=True, null=True)),
                ("last_opened_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("gate", "Шлагбаум"),
                            ("guest", "Гость"),
                            ("qr", "QR"),
                            ("alert", "Система"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="gates.accessuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=secrets.token_urlsafe, max_length=32, unique=True
                    ),
                ),
                ("guest_name", models.CharField(max_length=120)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("meeting", "Встреча с сотрудником"),
                            ("delivery", "Доставка"),
                            ("event", "Мероприятие"),
                            ("interview", "Собеседование"),
                            ("maintenance", "Техническое обслуживание"),
                            ("other", "Другое"),
                        ],
                        max_length=30,
                    ),
                ),
                ("valid_until", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_passes",
                        to="gates.accessuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=120)),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("student", "Студент"),
                            ("staff", "Преподаватель"),
                            ("guest", "Гость"),
                            ("admin", "Администратор"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("open", "Открыт"),
                            ("qr", "QR-код"),
                            ("denied", "Отказ"),
                        ],
                        max_length=20,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="gates.gate",
                    ),
                ),
                (
                    "guest_pass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gates.guestpass",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gates.accessuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
