# Generated by Django 4.2.7 on 2026-06-02 17:03

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):
    dependencies = [
        ("gates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestpass",
            name="code",
            field=models.CharField(
                default=secrets.token_urlsafe, max_length=80, unique=True
            ),
        ),
    ]
