# Generated by Django 4.2.7 on 2026-06-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gates", "0002_alter_guestpass_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessuser",
            name="password_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="subject_type",
            field=models.CharField(
                choices=[
                    ("student", "Студент"),
                    ("staff", "Преподаватель"),
                    ("guest", "Гость"),
                    ("security", "Охрана"),
                    ("admin", "Администратор"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="accessuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("student", "Студент"),
                    ("staff", "Преподаватель"),
                    ("security", "Охрана"),
                    ("admin", "Администратор"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
