# Generated by Django 4.2.7 on 2026-06-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gates", "0003_accessuser_password_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestpass",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="guestpass",
            name="guest_phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="guestpass",
            name="vehicle_plate",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
